### ISSUE TITLE
delete() is only available as callback-style, not promise-style

### ISSUE THREAD

**Issue by JoMersmann** [agsh/yapople#15]
https://github.com/agsh/yapople/blob/50a1b4fc86d5a167bedd2ada4a2e96cfd951a14e/lib/yapople.js#L464

delete() is missing here, so it's not available as promise-style. Documentation states all methodes are available in both stlyes

**Comment by savoiebz** [comment]
I've creating a pull request fixing the changes. @agsh Would you mind merging it?

First PR on GitHub so if there's anything wrong with it don't hesitate.

thank you,
Nice lib!
