### ISSUE TITLE
[Browser] process.versions.node is undefined

### ISSUE THREAD

**Issue by KaKi87** [agsh/yapople#17]
Hello,

I would like to run `yapople` browser-side from a Cypress test (to receive an account activation message), but I get the `process.versions.node is undefined` error.

Thanks

**Comment by agsh** [comment]
@KaKi87 Hi! It seems that Cypress is for browser, but this library is for node.js only. I.e. you can't receive emails directly from the browser without server. Node.js has its own [API](https://nodejs.org/dist/latest-v14.x/docs/api/) which doesn't present in browsers

**Comment by KaKi87** [comment]
I know, but are you sure it would be impossible to make it work Node-less in-browser ?

**Comment by agsh** [comment]
@KaKi87 Absolutely. You need to establish tcp/ip connection to the pop3 server to work with the mailbox. And in the browser this is impossible due to security restrictions.

**Comment by KaKi87** [comment]
Alright, then I'm setting up a local Node server to be called from browser.
Tanks
