### ISSUE TITLE
Mail listener

### ISSUE THREAD

**Issue by bgramaje** [agsh/yapople#20]
Hi!

Is there anyway to create a mail listener that is always listening for new emails and fires an event when a new email is being received? Thank you so much!

**Comment by agsh** [comment]
@boralbgra Hi! If you want to immediately get events from the server about new email, you should probably look at IMAP protocol realization. And for POP3 the best way is to use `setInterval`, for example. You can refer to this issue, btw: https://github.com/agsh/yapople/issues/18

**Comment by bgramaje** [comment]
Thank you so much!
