### ISSUE TITLE
client.retrieveAll() returns undefined

### ISSUE THREAD

**Issue by bgramaje** [agsh/yapople#22]
I was using this library with no problem at all, but suddenly I just stopped receiving any new mail, why would that happen? Thanks

**Comment by bgramaje** [comment]
That's the Error I am getting:

Error: .

    at Client.onData (D:\00_PROYECTOS\03_raul\02_app\server\node_modules\yapople\lib\yapople.js:108:19)
    at TLSSocket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:284:9)
    at TLSSocket.Readable.push (_stream_readable.js:223:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23)

**Comment by agsh** [comment]
@boralbgra Hi!
First of all, I updated the npm package 2 months ago to version 0.4.1. Which version do you use? Can you downgrade the package to 0.4.0 or 0.3.0 and test?

Also can you debug your app and put the breakpoint at line 103? And then send me the `sData` value when the error happens.
Because as I see, the error happens on line 108 and this means that you mail server sends something that differs from standard `+OK` or `-ERR`:
```js
        if (sData.substr(0, 4) === '-ERR') {
            err = new Error(sData.substring(5, sData.indexOf('\r\n')));
        } else if (sData.substr(0, 3) === '+OK') {
            succ = sData.substring(4, sData.indexOf('\r\n'));
        } else {
            err = new Error(sData);
        }
```

**Comment by bgramaje** [comment]
Yep I just printed out what the value of sData is (inside of the else statement), and it is a simple dot. What I recieve is a "."

. //This dot is the value printed out of sData. 

(node:2380) UnhandledPromiseRejectionWarning: Error: .

    at Client.onData (D:\00_PROYECTOS\03_raul\02_app\server\node_modules\yapople\lib\yapople.js:110:19)
    at TLSSocket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:284:9)
    at TLSSocket.Readable.push (_stream_readable.js:223:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:2380) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2380) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
.

**Comment by bgramaje** [comment]
I am retrieving all the emails from and outlook server, just in case this info is needed.

**Comment by bgramaje** [comment]
hi?

**Comment by agsh** [comment]
@boralbgra Hi! Dot mark in POP3 means the end of server message. It seems that you don't have any email in the mailbox.
You can also check the correctness of the transmission manually via telnet client
