### ISSUE TITLE
retrieveAll() never calls callback if there is zero messages

### ISSUE THREAD

**Issue by sidorares** [agsh/yapople#8]
Had to add this to work around:

``` js
    Client.prototype.retrieve = function(what, callback) {
       if (what.length === 0) {
               callback(null, []);
       }
```

is this behaviour intentional?

**Comment by agsh** [comment]
Found some bug in code, please check version from github:
`npm install https://github.com/agsh/yapople.git`

**Comment by agsh** [comment]
Done, please test it

**Comment by sidorares** [comment]
great, thanks @agsh
when this is going to be on npm?

**Comment by agsh** [comment]
Done

**Comment by sidorares** [comment]
thanks!
